### ISSUE TITLE
Grouped PostbackHandler

### ISSUE THREAD

**Issue by IronLady** [CasperLaiTW/laravel-fb-messenger#35]
Hi, 

Is it possible to group the postback handler by some pattern/prefix payload?

Lets say : 

PostbackRedHandler handle all postback data starting with PAYLOAD_RED_1, PAYLOAD_RED_2, ....
PostbackGreenHandler handle all postback data starting with PAYLOAD_GREEN_1, PAYLOAD_GREEN_2, ....

Thanks

**Comment by CasperLaiTW** [comment]
Thank you for your report.

I think you can defined children postbacks in your PostbackRedHandler.
PostbackRedHandler's `handle` function to trigger children postbacks.

I have no idea why need to grouped.

Maybe you can give me more information to plan it.

**Comment by IronLady** [comment]
Thanks. 

As far as I know using the current version. 
We have to create postback handler class for each payload right?
Or maybe there are other way to do this. 

Please let me know.

Thanks

**Comment by CasperLaiTW** [comment]
Yes, if you have 5 difference payload, you need to create 5 postback handler class.
I am planing to support regex, maybe few days can be released.

**Comment by IronLady** [comment]
Thanks.

For the simplicity, I think an array is enough. 
Something like $payload = ['PAYLOAD_A', 'PAYLOAD_B', 'PAYLOAD_C']

**Comment by CasperLaiTW** [comment]
Sound like good!!
Thank you for your proposal.
I will follow the proposal to implement.

**Comment by IronLady** [comment]
Wait, 

I think you're right. 
Regex allow more flexibility. 
+1 for using regex.

Thanks

**Comment by CasperLaiTW** [comment]
Release v1.1.2
