### ISSUE TITLE
Asynchronous Webhook

### ISSUE THREAD

**Issue by IronLady** [CasperLaiTW/laravel-fb-messenger#39]
Hi, Thanks for the regex feature before. 

I want to ask as per this docs https://developers.facebook.com/docs/messenger-platform/faq

It's recommended that after request sent by Facebook, we need to immediately answer with HTTP 200 code. I think we should implement queue in this. Send HTTP 200 to Facebook and handle the message after that.

Thanks

**Comment by CasperLaiTW** [comment]
I read this docs and it's recommended that using [Sender Action](https://developers.facebook.com/docs/messenger-platform/webhook-reference#response) to response HTTP 200.

We implement on bddd6f0 commit.

If it is not working on your project, can you get me more information to understand it

**Comment by CasperLaiTW** [comment]
But I found on postback handler did not response `Sender Action`, I will fix it.

**Comment by IronLady** [comment]
Thanks. That's what I was looking for. The Postback handler. 

Anyway, is there something like a "fail safe" in case there are some error in the code which may return any HTTP code other than 200?
Because, if Facebook doesn't get HTTP 200, it will keep sending the same message over and over again until 20 second.

**Comment by CasperLaiTW** [comment]
Now it's auto-type working, should need `fail safe`?
Because auto-type is request before any handlers.

If we need `fail safe`, I have idea that caching the request from Facebook and compare all request from Facebook. That's more loading on the server.
