### ISSUE TITLE
Account Link Button

### ISSUE THREAD

**Issue by umuttaymaz** [CasperLaiTW/laravel-fb-messenger#42]
Hey mate, it's great job. Congrats and thanks.

What about Log In and Log Out buttons?
Will you add them to your Button Collection?

**Comment by CasperLaiTW** [comment]
Hi, @umuttaymaz 

Did you mean account linking? [docs](https://developers.facebook.com/docs/messenger-platform/account-linking)

**Comment by umuttaymaz** [comment]
It would be cool but [this](https://developers.facebook.com/docs/messenger-platform/account-linking/link-account)

**Comment by CasperLaiTW** [comment]
Ok I will plan it to implement!!
Thank you for your request.
