### ISSUE TITLE
Hummingbird\Services\ManualChatbot - change 'run' function to 'send'

### ISSUE THREAD

**Issue by wheredidgogogo** [CasperLaiTW/laravel-fb-messenger#45]
I think you should change the name of 'run' function to 'send' in the manual chatbot to match the command for the FacebookMessenger class.

**Comment by CasperLaiTW** [comment]
Hi, @wheredidgogogo 

I should the class that in your project. Not Include the laravel-fb-messenger.

You can modify by yourself.
