### ISSUE TITLE
Account linking callback

### ISSUE THREAD

**Issue by jackcruden** [CasperLaiTW/laravel-fb-messenger#54]
I am not getting any callback from Facebook in the debug view when I 'link' my account.
Not sure if this is a bug or this functionality hasn't been built in yet.
https://developers.facebook.com/docs/messenger-platform/account-linking
Thanks

**Comment by CasperLaiTW** [comment]
Hi @jackcruden 

I'm sorry it's not bug, I'm only built account linking button.

I am no environment to link OAuth Service.

I think you want to get webhook is this, [Account Link Webhook](https://developers.facebook.com/docs/messenger-platform/webhook-reference/account-linking)?

I can make the handle to catch this webhook, and give you data
```json
{
  "sender":{
    "id":"USER_ID"
  },
  "recipient":{
    "id":"PAGE_ID"
  },
  "timestamp":1234567890,
  "account_linking":{
    "status":"linked",
    "authorization_code":"PASS_THROUGH_AUTHORIZATION_CODE"
  }
}    
``` 

Is it you want?

**Comment by jackcruden** [comment]
Oh, I assumed it was sent to the same webhook URL as the other 'subscriptions'. It looks like it's registered [here](https://developers.facebook.com/docs/messenger-platform/thread-settings/account-linking).

Thanks!

**Comment by jackcruden** [comment]
It would be a cool addition to the package though!
