### ISSUE TITLE
Request: Sample Laravel App

### ISSUE THREAD

**Issue by sbasi5576** [CasperLaiTW/laravel-fb-messenger#59]
Is it possible for you to publish a sample laravel app?

**Comment by joelcuevas** [comment]
I second that motion!

**Comment by CasperLaiTW** [comment]
I will publish quickly.

**Comment by sbasi5576** [comment]
Thanks.  Also we know that you are overseas.  But is there a way for you publish the interface to payments API?  We can test it in the US.

**Comment by CasperLaiTW** [comment]
Hi guys

I create a demo project.

https://github.com/CasperLaiTW/fb-messenger-demo

I think it can help you to make your app.

If example is not fully, please create an issues in demo repository which template you want to get.

I will add more template to demo project for help you

**Comment by CasperLaiTW** [comment]
@sbasi5576 
> Thanks. Also we know that you are overseas. But is there a way for you publish the interface to payments API? We can test it in the US.

I didn't get App to testing payments API.

If I make it only following documents, I can't check API working good or not.

Is any idea how can I request payment API?

**Comment by CasperLaiTW** [comment]
Main issue was solved

**Comment by joelcuevas** [comment]
Wow, what a great sample! Perfectly documented on the commits! Thanks! 😃

**Comment by sbasi5576** [comment]
Thanks.  I will try running it tonight.

**Comment by sbasi5576** [comment]
What would the webhook for the app?  I didn't see any entries in the routes.  probably will need an exception added to the midleware as well.

**Comment by CasperLaiTW** [comment]
can you run `php artisan route:list` you will get the webhook path.

if you don't want to use `/webhook` you can change config at `custom_url`

<img width="1255" alt="2017-02-10 2 19 25" src="https://cloud.githubusercontent.com/assets/5094008/22816258/f5e211ac-ef9b-11e6-937d-d37093c8de52.png">

**Comment by sbasi5576** [comment]
Yes i just saw that and submitted the webhook and it accepted it.  I have updated the .env file with my token and verify token as well.  But when i open the bot in messenger it doesn't do anything.  It also doesn't reply back even if I ping it.

**Comment by sbasi5576** [comment]
Also in the subscription are we supposed to have only messages, messaging_account_linking, messaging_optins, messaging_postbacks or can I we have more fields?

**Comment by CasperLaiTW** [comment]
We move to https://github.com/CasperLaiTW/fb-messenger-demo/issues/1 to discuss :)
