### ISSUE TITLE
Multi-tenancy with a custom route

### ISSUE THREAD

**Issue by sbasi5576** [CasperLaiTW/laravel-fb-messenger#60]
Can this module support multi-tenancy with a custom route?
For example, can we do something like this:

'custom_url' => '/chatbot/{bot-id}',

**Comment by CasperLaiTW** [comment]
Hi @sbasi5576 

I have no idea why should support multi-tenancy?

Can you explain your scenario?

**Comment by sbasi5576** [comment]
i may want to host more than one bot on the same laravel instance.  Instead of trying to create a separate route for each I may want to connect  use a route by passing an app number of some unique string.

**Comment by CasperLaiTW** [comment]
I think you can code in the `web.php` by yourself

```php
Route::get('/chatbot/{bot-id}', '\Casperlaitw\LaravelFbMessenger\Controllers\WebhookController@index');
Route::post('/chatbot/{bot-id}', '\Casperlaitw\LaravelFbMessenger\Controllers\WebhookController@receive');
```

If I make the `{bot-id}`, it' didn't use `bot-id` in library.

I think it a part of case.
