### ISSUE TITLE
Facebook SDK Integration

### ISSUE THREAD

**Issue by sbasi5576** [CasperLaiTW/laravel-fb-messenger#61]
Would this work with Facebook SDK, so that via OAuth, I can create a page, webhook  and messenger app / token creation?  There is a LaravelFacebookSdk but it is not obvious.

https://github.com/SammyK/LaravelFacebookSdk

**Comment by CasperLaiTW** [comment]
Do you mean [Account link](https://developers.facebook.com/docs/messenger-platform/thread-settings/account-linking)

**Comment by sbasi5576** [comment]
account link as well as ability to manage the pages on a user's behalf

**Comment by CasperLaiTW** [comment]
so I think duplicate #56
