### ISSUE TITLE
How can I send the respond later on?

### ISSUE THREAD

**Issue by m7vm7v** [CasperLaiTW/laravel-fb-messenger#63]
Hi, When someone is messaging I am receiving and storing the ID that facebook has provided.

How can I send to that user a message from my application.

I have tryed:

In my controller I have:

```
$fbMessanger = new FacebookMessageHandler();
$fbMessanger->sendPublishedMessage($user->facebook_id);
```

in FacebookMessageHandler:

```
public function sendPublishedMessage($user){
        $this->send(new Text($user, 'published'));
    }
```

But when I trigger it I got: NotCreateBotException in BaseHandler.php line 61

I need to have the option to message the facebook user from my application later on.
Now it receives the automated answer but I need to extend it by answering later on.

Would that be possible with this package?

Thanks

**Comment by CasperLaiTW** [comment]
Hi @m7vm7v 

Sure, you can send message by yourself

```php
$fbMessanger = new FacebookMessageHandler();
$fbMessanger->createBot(config('fb-messenger.app_token'));
$fbMessanger->sendPublishedMessage($user->facebook_id);
```

you miss the line 2 :)

**Comment by m7vm7v** [comment]
Thanks mate. That was it.
