### ISSUE TITLE
About ButtonCollection

### ISSUE THREAD

**Issue by youyi1314** [CasperLaiTW/laravel-fb-messenger#65]
if your element has more than one button, it can't add addCallButton, because it check if element more than one button, it will show ('The collection has more than one button, call button only use by itself.'), after i try to block 

> if (count($this->getElements()) > 0) {
>             throw new OnlyUseByItselfException(
>                 'The collection has more than one button, call button only use by itself.'
>             );
>         }

at **Collections/ButtonCollection.php**
than it work.

may I know why to block addCallButton if element more than one button?
is it some template disallow multi addCallButton?
Thanks

**Comment by CasperLaiTW** [comment]
Thank you catch it.

When I built call button, I notice document wrote only use call button without any buttons.

I think Facebook was updated.
