### ISSUE TITLE
route webhook not found 

### ISSUE THREAD

**Issue by phuongphally** [CasperLaiTW/laravel-fb-messenger#68]
1. 
![save](https://cloud.githubusercontent.com/assets/8773927/24347141/8949c010-1301-11e7-9116-199f7ca61a16.PNG)
![save1](https://cloud.githubusercontent.com/assets/8773927/24347142/894f1c5e-1301-11e7-86ba-455e14b59742.PNG)

**Comment by CasperLaiTW** [comment]
Hi @phuongphally 

The Controller will check `hub_mode ` and `hub_verify_token`.


please refer: https://github.com/CasperLaiTW/laravel-fb-messenger/blob/master/src/Controllers/WebhookController.php#L61-L63
