### ISSUE TITLE
Add support for creating Messenger Code

### ISSUE THREAD

**Issue by obaid** [CasperLaiTW/laravel-fb-messenger#74]
There should be a way to create Messenger Codes. The API should allow the user to define:

- Type
- Image Size
- Data

See https://developers.facebook.com/docs/messenger-platform/messenger-code for more details.

**Comment by CasperLaiTW** [comment]
Sure, I am planning :)

**Comment by obaid** [comment]
Awesome. Let me know if you need any help with it. :)

**Comment by CasperLaiTW** [comment]
ha - this week I am busy,  I think I will implement next week

If you want to send PR,  I look forward to seeing your PR :)

**Comment by CasperLaiTW** [comment]
Sorry be delayed. I am busy on my job.

enjoy it!

**Comment by obaid** [comment]
Thanks @CasperLaiTW! This is an awesome lib!
