### ISSUE TITLE
Customize menu

### ISSUE THREAD

**Issue by Iseldore** [CasperLaiTW/laravel-fb-messenger#79]
Hi!
Your package is very useful, I won a lot of hours!
I have a question, is this possible to customize the persistent menu?
I want a different menu based on user choices (like disable subscription on automatic messages if they accepted this option earlier), it would be perfect if it was possible!
Thanks!

**Comment by CasperLaiTW** [comment]
Hi @Iseldore 

did you mean setup persistent menu?

https://github.com/CasperLaiTW/laravel-fb-messenger/wiki/Commands#fbmenus

**Comment by Iseldore** [comment]
Hi @CasperLaiTW 
I mean a dynamic persistent menu, I would add a Postback button for a user during the conversation.
For what I understood, the menu is persistant (yeah, that's obvious), but I would know if it was possible to change this menu during the conversation. But maybe the menu is the same for every users and can't be changed ?

**Comment by CasperLaiTW** [comment]
Hi @Iseldore 

Yes, persistent must call Facebook API to changed and every users will get the same menus.

So I think you can't make dynamic persistent menu.

I think you have to make a conversation after user click on persistent menu and check user's status.

**Comment by Iseldore** [comment]
That's unfortunate :(

Anyway thanks again for your package and for your quick answer!
