### ISSUE TITLE
Dynamical config

### ISSUE THREAD

**Issue by elephantux** [CasperLaiTW/laravel-fb-messenger#84]
I want use messenger for several fb pages. 
Is it possible to dynamically add tokens?

**Comment by elephantux** [comment]
I think what I found solution
```
class Chatbot extends BaseHandler
{
    public function __construct()
    {
        $this->createBot(config('fb-messenger.app_token'));
    }
...
```

**Comment by elephantux** [comment]
But how to provide fb-messenger.app_secret & fb-messenger.verify_token to Bot?

**Comment by CasperLaiTW** [comment]
Hi, verify token can setup on `.env` file or [config](https://github.com/CasperLaiTW/laravel-fb-messenger/blob/master/config/fb-messenger.php)

otherwise you can use to `Config::set` to change it. 
```php
\Config::set('fb-messenger. verify_token', 'another verify token');
```
