### ISSUE TITLE
Method implementation missing

### ISSUE THREAD

**Issue by PrzemekTkaczyk** [CasperLaiTW/laravel-fb-messenger#92]
Hi, 
I have one error just after install package and try only publish config:

```$ php artisan vendor:publish --provider="Casperlaitw\LaravelFbMessenger\LaravelFbMessengerServiceProvider" --tag="config"

PHP Fatal error:  Class Casperlaitw\LaravelFbMessenger\Contracts\Debug\Handler contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Debug\ExceptionHandler::shouldReport) in /Users/przemyslawtkaczyk/Projects/optime/optime-crm/entry/vendor/casperlaitw/laravel-fb-messenger/src/Contracts/Debug/Handler.php on line 14
PHP Fatal error:  Uncaught Error: Cannot instantiate abstract class Casperlaitw\LaravelFbMessenger\Contracts\Debug\Handler in /Users/przemyslawtkaczyk/Projects/optime/optime-crm/entry/vendor/casperlaitw/laravel-fb-messenger/src/LaravelFbMessengerServiceProvider.php:58```

**Comment by CasperLaiTW** [comment]
Hi @PrzemekTkaczyk 
What's your laravel version?

**Comment by PrzemekTkaczyk** [comment]
Hi, 
nope, it is 5.8
I create a fork with some changes which works for me:
https://github.com/PrzemekTkaczyk/laravel-fb-messenger/commits/master
so:
1st - add missing method (I'm not sure if it should be true or false, yet)
2nd - change deprecated method (fire->dispatch)

**Comment by CasperLaiTW** [comment]
Cool, if you can send PR, I will review.

Thank you for contribute

**Comment by PrzemekTkaczyk** [comment]
but I'm not sure if it will work on older LV versions...

**Comment by CasperLaiTW** [comment]
ok, I will release new version (maybe v2.0.0)

the deprecated method after Laravel 5.4. so before Laravel 5.3 or less have to install v1.6.1 and >= 5.4 will be installed v2.0.0

**Comment by CasperLaiTW** [comment]
@PrzemekTkaczyk I rolled out new version, you can try `v2.0.0`

**Comment by PrzemekTkaczyk** [comment]
Thank you!
