### ISSUE TITLE
Error  Symfony\Component\ErrorHandler\Error\FatalError

### ISSUE THREAD

**Issue by dungadnetplus** [CasperLaiTW/laravel-fb-messenger#98]
Symfony\Component\ErrorHandler\Error\FatalError

  Declaration of Casperlaitw\LaravelFbMessenger\Contracts\Debug\Handler::report(
Exception $e) must be compatible with Illuminate\Contracts\Debug\ExceptionHandle
r::report(Throwable $e)

**Comment by CasperLaiTW** [comment]
Hi @dungadnetplus 

I released v3.0 for supporting laravel 7.X and 8.X

please upgrade package.

Cheers
